name: socialmedia
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.4.4
  flutter_vector_icons: ^0.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/sad.png
    - assets/signup.png
    - assets/welcome.png

  fonts:
    # w100 Thin, the least thick
    # w200 Extra-light
    # w300 Light
    # w400 Normal / regular / plain
    # w500 Medium
    # w600 Semi-bold
    # w700 Bold
    # w800 Extra-bold
    # w900 Black, the most thick
    - family: sfprotext
      fonts:
        - asset: fonts/sfprotext/SF-Pro-Text-Regular.otf
          weight: 300
        - asset: fonts/sfprotext/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: fonts/sfprotext/SF-Pro-Text-Bold.otf
          weight: 600
        - asset: fonts/sfprotext/SF-Pro-Text-Semibold.otf
          weight: 700

    - family: worksans
      fonts:
        - asset: fonts/worksans/WorkSans-Thin.ttf
          weight: 100
        - asset: fonts/worksans/WorkSans-Light.ttf
          weight: 200
        - asset: fonts/worksans/WorkSans-Regular.ttf
          weight: 300
        - asset: fonts/worksans/WorkSans-Semibold.ttf
          weight: 400
        - asset: fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: fonts/worksans/WorkSans-Bold.ttf
          weight: 600
        - asset: fonts/worksans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/worksans/WorkSans-Black.ttf
          weight: 900


